### PR TITLE
fix: Checkboxes in PR template

### PR DESCRIPTION
**Pull request by zackharley**
# Description
Checkboxes in PR template are not rendering correctly.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by lucas-manuel** [comment]
We actually had this set at `[ ]` before but decided to make it `[]` because people were doing `[x ]` instead of `[x]` too often

**Comment by zackharley** [comment]
It's broken in Markdown if we don't do that so all of the PRs will look
funky.

**Review by andrewlitt — DISMISSED** [review]

**Comment by zackharley** [comment]
@lucas-manuel Any thoughts?

**Comment by lucas-manuel** [comment]
Yeah nevermind actually, I agree with these changes

**Review by lucas-manuel — DISMISSED** [review]

**Review by ColinLMacLeod1 — DISMISSED** [review]

**Comment by ColinLMacLeod1** [comment]
@zackharley  it says there's conflicts, once they're resolved it's good to go

**Comment by andrewlitt** [comment]
oh god did I break it - shouldn't it be fix-pr-changes merged into develop??

**Review by lucas-manuel — APPROVED** [review]

**Comment by lucas-manuel** [comment]
Gonna merge this

**Pull request merged**
